CREATE VIEW ZAD1 AS
SELECT * 
FROM USP_25
WHERE OCENKA = 5
WITH CHECK OPTION;

SELECT * FROM USP_25;

SELECT * FROM ZAD1;

INSERT INTO ZAD1 VALUES (1001, 3415,4);

ALTER VIEW ZAD1 WITH SCHEMABINDING
AS SELECT UNUM, UDATE, OCENKA
FROM dbo.USP_25
WHERE OCENKA = 5
WITH CHECK OPTION;

CREATE UNIQUE CLUSTERED INDEX index_UNUM_UDATE ON ZAD1 (UNUM, UDATE);

EXEC sp_helpindex 'ZAD1';

CREATE VIEW ZAD3 AS
SELECT USP_25.*
FROM USP_25
JOIN PREDMETS_25 ON USP_25.PNUM = PREDMETS_25.PNUM
WHERE PREDMETS_25.PNAME = N'Математика'
AND CONVERT(VARCHAR(10), USP_25.UDATE, 120) = CONVERT(VARCHAR(10), DATEADD(day, -1, GETDATE()), 120);

INSERT INTO USP_25 
VALUES (
	(SELECT MAX(UNUM) FROM USP_25) + 1,
    5,                     
    DATEADD(day, -1, GETDATE()),  
    3412,
	(SELECT PNUM FROM PREDMETS_25 WHERE PNAME = 'Математика')
);    

SELECT * 
FROM USP_25 
WHERE PNUM = (SELECT PNUM FROM PREDMETS_25 WHERE PNAME = 'Математика')
  AND CONVERT(VARCHAR(10), UDATE, 120) = CONVERT(VARCHAR(10), DATEADD(day, -1, GETDATE()), 120);

SELECT * FROM ZAD3;