ALTER TABLE USP_25
ADD CONSTRAINT PK_USP_25 PRIMARY KEY (UNUM);

ALTER TABLE TEACHERS_25
ADD CONSTRAINT PK_TEACHERS_25 PRIMARY KEY (TNUM);

ALTER TABLE PREDMETS_25
ADD CONSTRAINT PK_PREDMETS_25 PRIMARY KEY (PNUM);

